In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob as gb
import cv2
from PIL import Image
import os
from sklearn.model_selection import train_test_split

In [2]:
import cv2

image = cv2.imread(r'C:\Users\Kusha\Desktop\masters\final_sem\project\Umpire_Gesture_Recognition-main\Umpire_Gesture_Recognition-main\data\destination_data\train_data\leg_byes\Leg_Bye-1-_jpeg.rf.5540c21784e157e63f799a41a29abebf.jpg')
print(image.shape)

(640, 640, 3)


In [3]:
from sklearn.model_selection import train_test_split

def load_images_and_labels_from_folder(folder):
    images = []
    labels = []
    for class_folder in os.listdir(folder):
        class_path = os.path.join(folder, class_folder)
        if os.path.isdir(class_path):
            for filename in os.listdir(class_path):
                # Load image and handle errors
                try:
                    img = Image.open(os.path.join(class_path, filename))
                    # Resize image if necessary
                    img = img.resize((224, 224))  # Adjust size as needed
                    images.append(np.array(img))  # Convert image to array
                    labels.append(class_folder)
                except Exception as e:
                    print(f"Error loading image: {e}")
    return images, labels

# Set your train and test data directories
train_dir = r"C:\Users\Kusha\Desktop\masters\final_sem\project\knn_rff\train_data"
test_dir = r"C:\Users\Kusha\Desktop\masters\final_sem\project\knn_rff\test_data"

# Load train images and labels
train_images, train_labels = load_images_and_labels_from_folder(train_dir)

# Load test images and labels
test_images, test_labels = load_images_and_labels_from_folder(test_dir)

# Convert train images to arrays
X_train = np.array(train_images)

# Convert test images to arrays
X_test = np.array(test_images)

# Convert labels to numerical values
label_to_index = {label: i for i, label in enumerate(set(train_labels))}
train_labels = np.array([label_to_index[label] for label in train_labels])
test_labels = np.array([label_to_index[label] for label in test_labels])

# Split data into train and test sets
X_train, X_val, y_train, y_val = train_test_split(X_train, train_labels, test_size=0.2, random_state=42)

# Now you have your train, validation, and test data split into arrays and labels.
# X_train, X_val, and X_test contain the images as arrays, while y_train, y_val, and y_test contain the corresponding labels.


In [4]:
X_train

array([[[[199, 206, 212],
         [199, 206, 212],
         [199, 206, 212],
         ...,
         [241, 238, 233],
         [243, 240, 235],
         [241, 239, 234]],

        [[199, 206, 212],
         [200, 207, 213],
         [200, 207, 213],
         ...,
         [238, 237, 232],
         [239, 238, 233],
         [238, 237, 232]],

        [[200, 207, 213],
         [200, 207, 213],
         [199, 206, 212],
         ...,
         [236, 235, 230],
         [235, 234, 229],
         [235, 234, 229]],

        ...,

        [[146, 155, 153],
         [151, 160, 157],
         [202, 210, 208],
         ...,
         [199, 209, 211],
         [198, 208, 209],
         [198, 208, 208]],

        [[141, 150, 144],
         [138, 148, 141],
         [148, 158, 153],
         ...,
         [196, 206, 206],
         [194, 204, 203],
         [193, 204, 201]],

        [[134, 144, 136],
         [135, 145, 137],
         [133, 143, 135],
         ...,
         [192, 201, 198],
        

In [5]:
y_train

array([0, 0, 1, 4, 2, 5, 0, 0, 1, 2, 4, 1, 1, 4, 1, 1, 3, 1, 2, 2, 4, 4,
       0, 5, 1, 5, 5, 4, 1, 4, 1, 0, 0, 5, 0, 0, 4, 1, 0, 4, 1, 5, 5, 0,
       3, 4, 4, 5, 4, 5, 2, 0, 4, 1, 0, 4, 1, 0, 4, 2, 1, 5, 2, 4, 5, 2,
       1, 1, 4, 1, 0, 2, 0, 0, 2, 1, 5, 1, 4, 4, 4, 2, 4, 5, 5, 2, 5, 4,
       0, 4, 5, 2, 2, 5, 2, 1, 1, 5, 4, 1, 1, 2, 4, 4, 5, 0, 4, 5, 4, 4,
       4, 1, 1, 1, 2, 4, 3, 4, 0, 1, 4, 0, 2, 2, 4, 2, 4, 0, 5, 0, 4, 4,
       1, 5, 4, 1, 2, 1, 1, 5, 1, 1, 0, 2, 1, 0, 2, 2, 5, 4, 1, 2, 4, 2,
       0, 1, 5, 2, 2, 5, 3, 0, 2, 5, 5, 0, 0, 4, 4, 3, 5, 5, 4, 5, 5, 1,
       0, 5, 2, 0, 1, 0, 1, 1, 4, 1, 4, 5, 1, 4, 2, 4, 4, 0, 2, 1, 5, 1,
       2, 1, 1, 2, 2, 4, 2, 0, 5, 0, 4, 4, 1, 5, 4, 4, 1, 4, 5, 2, 5, 3,
       5, 0, 1, 1, 2, 5, 0, 1, 5, 4, 5, 2, 4, 2, 1, 2, 4, 4, 4, 0, 5, 2,
       1, 4, 5, 1, 4, 4, 1, 5, 2, 2, 5, 1, 4, 0, 1, 1, 5, 0, 5, 2, 2, 2,
       4, 1, 1, 1, 2, 1, 5, 5, 4, 5, 4, 4, 1, 5, 5, 1, 2, 0, 1, 1, 4, 5,
       4, 4, 4, 4, 5, 5, 4, 2, 2, 4, 5, 1, 1, 5, 4,

In [6]:
X_val

array([[[[  0,   7,   1],
         [  0,   7,   0],
         [  0,   6,   1],
         ...,
         [  0,   4,   0],
         [  0,   0,   5],
         [  0,   0,   6]],

        [[  7,  16,   5],
         [ 16,  26,  10],
         [ 16,  29,  12],
         ...,
         [ 44,  56,  21],
         [ 10,  14,   6],
         [  1,   2,   3]],

        [[ 44,  58,  24],
         [109, 127,  76],
         [122, 143,  83],
         ...,
         [108, 127,  66],
         [ 19,  28,   9],
         [  0,   3,   1]],

        ...,

        [[ 40,  50,  15],
         [108, 127,  54],
         [122, 150,  49],
         ...,
         [ 97, 116,  44],
         [  6,  14,   0],
         [  0,   2,   3]],

        [[ 40,  50,  15],
         [108, 128,  54],
         [122, 150,  49],
         ...,
         [105, 124,  59],
         [ 18,  27,  11],
         [ 12,  16,   9]],

        [[ 41,  51,  16],
         [109, 128,  54],
         [122, 150,  49],
         ...,
         [ 69,  88,  32],
        

In [7]:
y_val

array([1, 5, 5, 4, 1, 4, 1, 3, 2, 0, 2, 1, 1, 5, 1, 5, 1, 0, 1, 4, 5, 1,
       4, 2, 4, 5, 4, 1, 2, 4, 3, 1, 2, 5, 1, 1, 4, 4, 0, 0, 1, 2, 2, 5,
       1, 4, 0, 4, 5, 4, 5, 1, 5, 4, 0, 2, 0, 2, 4, 4, 4, 0, 2, 4, 5, 4,
       0, 2, 2, 2, 4, 2, 2, 1, 0, 0, 1, 0, 5, 0, 2, 1, 4, 4, 0, 5, 1, 2,
       3, 4, 1, 1, 2, 1, 4, 1, 4, 0, 1, 4, 2, 2, 4, 4, 2, 4, 1, 0, 0, 1,
       4, 0, 2, 4, 0, 4, 0, 1, 2, 2, 1, 0, 2])

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train.reshape(len(X_train), -1), y_train)



RandomForestClassifier(random_state=42)

In [9]:
# Predict on the validation set
y_val_pred = rf_classifier.predict(X_val.reshape(len(X_val), -1))
y_val_pred

array([1, 5, 5, 4, 0, 1, 1, 4, 2, 1, 2, 1, 1, 5, 4, 5, 1, 1, 1, 1, 5, 0,
       4, 2, 0, 5, 4, 1, 2, 4, 1, 1, 2, 5, 1, 1, 4, 4, 0, 4, 4, 2, 0, 5,
       4, 0, 0, 4, 5, 4, 5, 1, 5, 4, 0, 5, 0, 2, 4, 4, 0, 4, 5, 0, 5, 4,
       1, 0, 2, 2, 4, 2, 2, 1, 0, 5, 1, 0, 5, 0, 5, 1, 4, 5, 0, 1, 1, 2,
       0, 1, 1, 1, 2, 1, 5, 1, 4, 0, 1, 2, 2, 5, 1, 5, 2, 1, 1, 0, 1, 1,
       4, 5, 2, 1, 5, 4, 2, 0, 2, 2, 1, 0, 2])

In [10]:
# Calculate accuracy on the validation set
val_accuracy = accuracy_score(y_val, y_val_pred)
print("Validation Accuracy:", val_accuracy)

Validation Accuracy: 0.6747967479674797


In [11]:
# Predict on the test set
y_test_pred = rf_classifier.predict(X_test.reshape(len(X_test), -1))

ValueError: cannot reshape array of size 0 into shape (0,newaxis)

In [12]:
# Calculate accuracy on the test set
test_accuracy = accuracy_score(test_labels, y_test_pred)
print("Test Accuracy:", test_accuracy)

NameError: name 'y_test_pred' is not defined